import { lazy, Suspense, useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronRight, Search, Target, Upload, X } from 'lucide-react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import remarkMath from 'remark-math'
import rehypeKatex from 'rehype-katex'
import 'katex/dist/katex.min.css'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useToast } from '@/components/ui/use-toast'
import { DetailBackButton } from '@/components/common/DetailBackButton'
import type { TagFrequency } from '@/components/analytics/TopicFrequencyChart'
import { ApiError, apiFetch } from '@/lib/api'
import { useAuthStore } from '@/store/auth'
import { AIChatPanel } from '../components/ai/AIChatPanel'
import { SmartNotesDisplay } from '@/components/study/SmartNotesDisplay'
import { UnifiedUploadModal } from '@/components/study/UnifiedUploadModal'

const PYQFeed = lazy(() => import('@/components/pyqs/PYQFeed').then(m => ({ default: m.PYQFeed })))
.catch(err => console.error(err))